---
title: "Assignment 1: Introduction"
author: "Erin Lee"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.

7.  Initial here to acknowledge that you did not use AI at all in completing this assignment:E.L

---

## 1) Concept and Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I do not have previous experience with data analytics, R, or Git, either through formal coursework or informal training. 

2. Are there any components of the course about which you feel confident?

> Answer: Not at this time. The course content and tools are new to me.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I feel apprehensive about the programming and version control components, as these tools are new to me.

4. Describe a dataset you have used in the past. Explain whether it was a primary or secondary dataset. 

> Answer: In my previous work at South Korea’s Ministry of Trade, Industry and Energy, I was exposed to electricity market statistics that included monthly generation by energy source and electricity market prices.This was a secondary dataset, as the data were routinely collected and compiled by government agencies for administrative and policy purposes.

5. Would you describe the day of the month as a nominal, ordinal, interval, or ratio number? Explain your reasoning.

> Answer: The day of the month is interval data because it has meaningful and equal intervals (for example, the difference between day 5 and day 10 is 5 days) and does not have a true absolute zero.

---

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/erinchlee/EDE_Spring2026

---

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
